# Run `travis lint` when changing this file to avoid breaking the build.


# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

cache:
  directories:
  # zipkin-ui gets dependencies via NPM
  - $HOME/.npm
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

before_install:
  # parameters used during a release
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  # skip license on travis due to #1512
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dlicense.skip=true

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "BlLb2fp9V5I+hJdqYhYVga535LhrhlsgIrhDUDE7X6VHo5CNk3ORXuVDhNx7s7IKSCyE9BkIrkbkySTLb5jMM5Gagb8IXbmOo0Gu1P7fAtIRucfJl/pcAx5HDFs82+urOKkTmhxwUYI3uXWsUG4qYBqNqKuUP7GrK5uDoiGO5cwVjElbJRtmBmQMuJUmtceZQCoiTb+fYdin7f3zyFbaJyHlZo79ZW4NW4J7Op3laaBhrD37Opp1qVhjAP9NKfPiRtD7SJrCaLRPhfvJoHY5F+RbIdIIXFY6nIDVFO2vBN7Cq50Mpm18tnKNJzWRgiBNZXfKNm2Y1kRhzysZZ2W65zTiyahSTEgIgdMJPN14Omkjgbw1XFDWp+YHJ8tfZtvR8I3P5Huc6OYLGg4zytcOkClCxy4J1Kv1JdVjUnOGfNOYh8+MSN88CyaAcCG/S83KbvxtP/8iGwhu6qMQ+zYUoDMsTld8fhEaNlBLRrNQ2QAY2YemKG/YwBc1VSwkAFAA6+wnyvhdy+tViZbL3Fgc6BgaGmoKNtpCkDg5ceaG1yZQQgnJDzko0FISrY5JxDoCkZNLlCcLrM23Gcy/YVibh/7YdmTbkIvubhH7OZgLBdxyRuh9eIHXGceIuxebCBnrAynrNhFICqI0o4fo8a1vD/sgjE7cj5stvuGyr3M+ipA="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "r3KtC8exADkNXd9pKRhRuOJK4C7+/8w/gb5kHj00w1gAEZjzqTvKhCs5h/xP3h3ER9PcxFGeXRcTYeVzHlhDS/ktDS1kI0+kS3Fqsch4CfvS1t0QAhcWFH7d2gv9MwCFvWINZj3WqODZiuL3kKp+YUD2kx9F0Va7pIWDR17G6wztToC1VGXTUOUHmnFoJ8XZx/jJGvTG02+Hqzyd2/L77zVye8nczXL6uMlPgMJD7AVQ2Twfm6ymjv1t+W9HM3sA6QPV/aW41eLPJJ6WMzLOx9mA0CCzKeh3OCxlXNFLBQjYd5Ttt1TZ338ztoDyZejwsIKcnRvbWc8WmUZxwgXrBb2wpGX1iux8S9RwxdmAZ6oYaloAE28Ov/pJkyCh2bQDfBSMLykawdR9gcqOSizHue5zSHDLI+Ew7Y1P5t3TNeVY7q4Q+DjiG8CLDwBLh+iy7PmwLE1Z98vNTGf8AfI26UNU7sphGJR9EbCmxOpy4nr8oVdInxRDeaDLl7rrHS5XwiJxlLXoS72OTuANmNoJCMtPEprdWkSJwdx2CnLDZ9Ogd7oMSUoFpsnDk+oYNXO8mGeTXmabxJyUY0LWc88iEVNUQNdF3LvhoMsEVb7Pmc406NMXaJbjf75cRDbEUmO8noS02hXuJx4mQ4YVLHLw5sisHJJ/AtS3Xw1z8orjhJs="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "YepJTAqvz3YDXU540McoDFvRcbIECTycAg/1yvB4iWtnF8ZrILO5KYkPebUKUmrBRwYGNXfLBit/9fhhS1Ubh52/NTugy6tr96MNoyu1UL1qscqpP4FbFdqNfKfcPUOWaHWqwyGRzogEJuInYXuGj6QKl9kYVKmpEuOqCEFV6x5alzmki0Frue9ZCyDfPX/TxYzAW2nWrtDdylzxIl86bdoxWqcUgh0nnj+dmGcJ7gKVaBTYTQE48xgEA9ZRvpY04lcyuU0fPvAJ8jjtol/7r/rewIs9QiBR+xayX40q9k69R7kQoYH01sPzVqpA1pVKUcmTAx1vkxlZIWH0UVkjcxbXmWSl1eTJBIZQfgthhIMDm04BQnJvsaa0Aw7k9B+GuIqvdnen4ppdPwmXOiffzZOkVZW5BPgKy63PiMeOZm6gpIJ3MoWSntQ+T9AQPpD9E5UrXhNmGMGZPgm7FwglXFgHhz7Rw9v3slqh/HI+IRSjUvRxiPL2a8m3KieI8jDKKOC3aurEcz7yTr+AC7Osri/16YvVSbJ8UuWIMxPYNuh4NogmQfVIFmiy36zMQ1yDHESq6mA8/WX8gj1ymiwbDylzk1eTJwY/63M8h7OxDtqi84JkafHzKbKudbJErLLlT+R0IaVxVFY1C/wu/rbjUYaQYFbfPuqm4cOGss/Ivus="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "11P7Dfi45vBezZnVNd+S6u7H2fX9F9JbZsTXpFJFyh3RmkBMUp1hq+6jyFelWH6cUh68WVNt0tvLLXPxzW0bKSsOExPpUAnlApGmWHspDzLZYVf5/hM5U0oUEvgqFgZZ+NGcsfSMp8LPBFiCmlz0T19Xr8H8i9iYionet2vdFp4wfglRKdQcHKcOE/V/7p0DCyoAFr76JoKrPDdO/TX+vAldTMkXK5miPekoKuZeGKdKmkjG5PSyVjXFR/1IYILU/m5MvPkbnd/3zif1lfMhOt60lcWLkvfmKVB+O8IO6iPZL7WFvZ/HS9EP5wFk8BUepKAN6Q/5QjTrNoB00dygdlRt8O5vmCijhxuGoMhyVaEs2kjg8y7Ox1csQ0KpILtz0Mn8agVR9croIc/30pNlSMcIpqa7UBeUC66pAR29RH9juRUQVgexHAo5A6Zs2NJYxnQ+iEW7gxVMZoUEsYTA6pOqjrQ5rQP/bisIJ1Lsyz+AKsssOJOfrobsJe62P8eDcEYLkkXDbJm5llN+iT9Q2hWOQZeS4H/Ve+09sUHQdpl0fqV5i6ANbeLpEkRupUnEChWuVbVdY/Pw4nWwrTXYurJm3mmoYIAuYdxJDUth5mNGD0RxmB5keDry+gp59PfaWY7iTjDiBP2ZfUGtz7XjkFnVnnLwgef18JNAP6hSqug="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "B8rblo0GKDBegXn5Vb01mhdlmRkbMJLDmgPQQfDX518Fl+m9UamJVOTQzDP8sApZGJyuVC9WpIO+fxGeoxjOWlTFC/i9b3mZCpNLg8KRRFk7OjDKf4xwT6UyBwkXlY8q0/htu5hwsvGp7ICBkWxs2ZQWu9OGwH7D2IH8Ehd+0cuwQyROIsPx++p+uhMv+phJWPgTSZ4vdIy/JvGZexF19eZGRKWmxEnrB+SMMYwsmIM1PghEhW7MahPs5Ly06HloDsjDbTnKU8AeFk+NDkQ4AvAu12fhg329UGPF14BVKfGx2hjnT9yj/PuL0az+YkGRmp2qiwol9ELd0vTfIY/Ld6Xa+82r3vnwpm7SUeOmzW2SyC61hZRxWLCuU/D0mPnPMUbkWVi12lQfWQhE/maka/6Odm48IlD/ZLqtg7bc0GU4sDT/Kf+MQlZf++Q03R6FuHDRPxZP0pXCEAF+P4MV3cwSZG/2X7A69QcFr5Eh+4e9YBy1ORHsEPXgQ1RmFcAIMfVMYia1GzkNelE4njXlnw3tolvUU+KUnsawqQ1DJbctoi2YEP14Ugy8X33t/qUnto2s88TlSlPYT4FNMytI7pwqjkHJ9zwsCzsbNKy+Gkg34Xzs4RrQz5k4lKe+RoRv3CxndElM2tHGkefMW5gbNGmDNMtRPeVLoEbnryIbiqY="
